services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DOMAIN_URL=${DOMAIN_URL}
      - MONGO_URI=${MONGO_URI}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URL=${REDIS_URL}
      - BANK_ID=${BANK_ID}
      - ACCOUNT_NO=${ACCOUNT_NO}
      - ACCOUNT_NAME=${ACCOUNT_NAME}
      - VNP_TMNCODE=${VNP_TMNCODE}
      - VNP_HASHSECRET=${VNP_HASHSECRET}
      - VNP_URL=${VNP_URL}
      - VNP_RETURN_URL=${VNP_RETURN_URL}
      - VNP_IPN_URL=${VNP_IPN_URL}

volumes:
  esdata:
    driver_opts:
      type: none
      device: '/mnt/d/HCMUS/CN/WEB/Final Project/car-services/data/elasticsearch' # Windows path to Docker path
      o: bind
